task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 80
remap_mscoco_category: True

train_dataloader: 
  total_batch_size: 64
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /kaggle/input/coco128-jsonsv3/images/train2017/
    ann_file: /kaggle/input/coco128-jsonsv3/annotations/instances_train2017.json
    # img_folder: /kaggle/input/coco2017-txts/images/train2017/
    # ann_file: /kaggle/input/coco2017-txts/annotations/instances_train2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  total_batch_size: 8
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /kaggle/input/coco128-jsonsv3/images/val2017/
    ann_file: /kaggle/input/coco128-jsonsv3/annotations/instances_val2017.json
    # img_folder: /kaggle/input/coco2017-txts/images/val2017
    # ann_file: /kaggle/input/coco2017-txts/annotations/instances_val2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
