task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 4 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  total_batch_size: 48
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/jiangnan-dataset/640px-jiangnan/images/train/
    ann_file: /kaggle/input/jiangnan-dataset/jiangnan_640px-jiangnan/annotations/annotations_train.json
    # img_folder: /data/yourdataset/train
    # ann_file: /data/yourdataset/train/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 8 #4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  total_batch_size: 8
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/jiangnan-dataset/640px-jiangnan/images/val/
    ann_file: /kaggle/input/jiangnan-dataset/jiangnan_640px-jiangnan/annotations/annotations_val.json
    # img_folder: /data/yourdataset/val
    # ann_file: /data/yourdataset/val/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
